export const USERS = {
  GET: {
    REQUEST: 'GET_USERS_REQUEST',
    SUCCESS: 'GET_USERS_SUCCESS',
    FAILURE: 'GET_USERS_FAILURE',
  },
  GET_USER: {
    REQUEST: 'GET_USER_REQUEST',
    SUCCESS: 'GET_USER_SUCCESS',
    FAILURE: 'GET_USER_FAILURE',
  },
  ADD_USER: {
    REQUEST: 'ADD_USER_REQUEST',
    SUCCESS: 'ADD_USER_SUCCESS',
    FAILURE: 'ADD_USER_FAILURE',
  },
  UPDATE_USER: {
    REQUEST: 'UPDATE_USER_REQUEST',
    SUCCESS: 'UPDATE_USER_SUCCESS',
    FAILURE: 'UPDATE_USER_FAILURE',
  },
  DELETE_USER: {
    REQUEST: 'DELETE_USER_REQUEST',
    SUCCESS: 'DELETE_USER_SUCCESS',
    FAILURE: 'DELETE_USER_FAILURE',
  }
}