export const AUTHORS = {
  GET: {
    REQUEST: 'GET_AUTHORS_REQUEST',
    SUCCESS: 'GET_AUTHORS_SUCCESS',
    FAILURE: 'GET_AUTHORS_FAILURE',
  },
  ADD: {
    REQUEST: 'ADD_AUTHORS_REQUEST',
    SUCCESS: 'ADD_AUTHORS_SUCCESS',
    FAILURE: 'ADD_AUTHORS_FAILURE',
  },
  UPDATE: {
    REQUEST: 'UPDATE_AUTHOR_REQUEST',
    SUCCESS: 'UPDATE_AUTHOR_SUCCESS',
    FAILURE: 'UPDATE_AUTHOR_FAILURE',
  },
  DELETE: {
    REQUEST: 'DELETE_AUTHOR_REQUEST',
    SUCCESS: 'DELETE_AUTHOR_SUCCESS',
    FAILURE: 'DELETE_AUTHOR_FAILURE',
  }
}