export const BOOKS = {
  GET: {
    REQUEST: 'GET_BOOKS_REQUEST',
    SUCCESS: 'GET_BOOKS_SUCCESS',
    FAILURE: 'GET_BOOKS_FAILURE',
  },
  GET_BY_ID: {
    REQUEST: 'GET_BOOKS_BY_ID_REQUEST',
    SUCCESS: 'GET_BOOKS_BY_ID_SUCCESS',
    FAILURE: 'GET_BOOKS_BY_ID_FAILURE',
  },
  ADD: {
    REQUEST: 'ADD_BOOKS_REQUEST',
    SUCCESS: 'ADD_BOOKS_SUCCESS',
    FAILURE: 'ADD_BOOKS_FAILURE',
  },
  UPDATE: {
    REQUEST: 'UPDATE_BOOKS_REQUEST',
    SUCCESS: 'UPDATE_BOOKS_SUCCESS',
    FAILURE: 'UPDATE_BOOKS_FAILURE',
  },
  DELETE: {
    REQUEST: 'DELETE_BOOKS_REQUEST',
    SUCCESS: 'DELETE_BOOKS_SUCCESS',
    FAILURE: 'DELETE_BOOKS_FAILURE',
  }
}